import { StyleSheet } from "react-native";
import { KARELA } from "./designSystem";

export const styles = StyleSheet.create({
  scrollContent: { padding: 24, paddingTop: 60 },
  header: { marginBottom: 40 },
  logo: { width: 60, height: 60, marginBottom: 20, tintColor: KARELA.color.brand },
  title: {
    fontSize: KARELA.size.display,
    fontFamily: KARELA.font.bold,
    color: KARELA.color.textPrimary,
    lineHeight: 40,
  },
  form: { gap: KARELA.space.xl },
  inputContainer: {
    borderBottomWidth: 1,
    borderBottomColor: KARELA.color.surfaceSoft,
    paddingBottom: 5,
  },
  input: {
    fontFamily: KARELA.font.regular,
    color: KARELA.color.textPrimary,
    fontSize: 16,
    paddingVertical: 10,
  },
  rowBetween: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 5,
  },
  row: { flexDirection: "row", alignItems: "center" },
  checkbox: {
    width: 18,
    height: 18,
    backgroundColor: KARELA.color.surfaceSoft,
    marginRight: KARELA.space.sm,
    borderRadius: KARELA.space.xs,
    justifyContent: "center",
    alignItems: "center",
  },
  checkboxChecked: { backgroundColor: KARELA.color.brand },
  label: { color: KARELA.color.textMuted, fontFamily: KARELA.font.regular, fontSize: KARELA.size.body },
  forgotPass: { color: KARELA.color.textMuted, fontFamily: KARELA.font.regular, fontSize: KARELA.size.body },
  loginBtn: { marginTop: KARELA.space.xl, borderRadius: KARELA.radius.xl, overflow: "hidden" },
  gradientBtn: {
    paddingVertical: KARELA.space.lg,
    alignItems: "center",
    justifyContent: "center",
  },
  loginBtnText: { color: KARELA.color.textPrimary, fontFamily: KARELA.font.bold, fontSize: KARELA.size.h2 },
  dividerContainer: { alignItems: "center", marginVertical: 30 },
  dividerText: { color: KARELA.color.textFaint, fontFamily: KARELA.font.regular },
  socialStack: { gap: 15 },
  socialBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: KARELA.space.lg,
    borderRadius: KARELA.radius.xl,
  },
  socialBtnText: { fontFamily: KARELA.font.medium, fontSize: 16 },
  footer: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: KARELA.space.xxxl,
    marginBottom: KARELA.space.xl,
  },
  footerText: { color: KARELA.color.textMuted, fontFamily: KARELA.font.regular },
  signupText: { color: KARELA.color.brand, fontFamily: KARELA.font.bold },
});
