import { Dimensions, Platform, StyleSheet } from "react-native";

// Define the "iOS Hack" dash pattern
const iOSSolidFiber = [100000, 0];

export const MAP_CONFIG = {
  futurePath: {
    strokeColor: "rgba(124, 242, 5, 0.4)",
    strokeWidth: 8,
    zIndex: 100,
    // Applies the dash trick only on iOS to kill the blue line
    lineDashPattern: Platform.OS === 'ios' ? iOSSolidFiber : undefined,
  },
  traversedPath: {
    strokeColor: "rgba(124, 242, 5, 1.0)",
    strokeWidth: 8,
    zIndex: 200,
    lineDashPattern: Platform.OS === 'ios' ? iOSSolidFiber : undefined,
  },
  questPath: {
    strokeColor: "rgba(255, 215, 0, 1.0)",
    strokeWidth: 6,
    zIndex: 150,
    // Gold line usually works better without the hack, but add if it turns blue
    lineDashPattern: Platform.OS === 'ios' ? iOSSolidFiber : undefined,
  }
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  map: {
    width: Dimensions.get("window").width,
    height: Dimensions.get("window").height,
  },
  // --- Markers ---
  marker: {
    width: 30,
    height: 30,
    borderRadius: 10,
    backgroundColor: "#7CF205",
    borderWidth: 3,
    borderColor: "#fff",
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  markerWrapper: {
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
    elevation: 0, 
    borderWidth: 0, 
  },
  ghostMarker: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "rgba(32, 159, 119, 1)", 
    borderWidth: 2,
    borderColor: "#fff",
    margin: 0, 
    padding: 0,
  },
  // --- Quest System Styles ---
  checkpointLabel: {
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderWidth: 1,
    borderColor: '#FFD700',
    marginBottom: -5,
    zIndex: 1,
  },
  checkpointText: {
    color: '#FFD700',
    fontSize: 10,
    fontWeight: 'bold',
  },
  questCard: {
    position: 'absolute',
    top: 110,
    alignSelf: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: '#FFD700',
    alignItems: 'center',
    elevation: 10,
  },
  rewardText: {
    color: '#FFD700',
    fontWeight: 'bold',
    fontSize: 16,
    letterSpacing: 0.5,
  },
  flagSpawner: {
    position: 'absolute',
    top: 50,
    right: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 25,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#FFD700',
    elevation: 8,
  },
  flagCountBadge: {
    position: 'absolute',
    top: -8,
    left: -8,
    backgroundColor: '#FF3B30',
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
    borderWidth: 1.5,
    borderColor: 'white',
  },
  flagCountText: {
    color: 'white',
    fontSize: 10,
    fontWeight: 'bold',
  },
  // --- Trash System ---
  trashBinContainer: {
    position: 'absolute',
    bottom: 120,
    alignSelf: 'center',
    alignItems: 'center',
    width: '100%',
    zIndex: 999,
  },
  trashBin: {
    backgroundColor: 'rgba(255, 59, 48, 0.2)',
    padding: 20,
    borderRadius: 60,
    borderWidth: 2,
    borderColor: '#FF3B30',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    width: 120,
    height: 120,
  },
  trashText: {
    color: '#FF3B30',
    fontSize: 10,
    fontWeight: 'bold',
    marginTop: 5,
    textAlign: 'center',
  },
  // --- UI Elements ---
  backButton: {
    position: 'absolute',
    top: 50,
    left: 20,
    backgroundColor: '#7CF205',
    width: 45,
    height: 45,
    borderRadius: 22.5,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  buttonContainer: {
    position: "absolute",
    bottom: 40,
    width: "100%",
    alignItems: "center",
  },
  actionButton: {
    paddingVertical: 15,
    paddingHorizontal: 40,
    borderRadius: 30,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "bold",
    letterSpacing: 1,
  },
});