import { StyleSheet } from "react-native";

export const ProgressScreenUI = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#000" },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 20,
    paddingTop: 50,
  },
  profileSection: { alignItems: "center", marginBottom: 20 },
  avatarWrapper: {
    width: 120,
    height: 120,
    borderRadius: 60,
    overflow: "hidden",
    marginBottom: 10,
  },
  avatarGradient: { flex: 1, padding: 4 },
  avatarImage: { flex: 1, borderRadius: 60, backgroundColor: "#1A1A1A" },
  rankText: { color: "white", fontSize: 18, fontWeight: "900" },
  xpText: { color: "#666", fontSize: 12, marginBottom: 15 },
  rankButton: {
    width: "60%",
    height: 45,
    borderRadius: 25,
    overflow: "hidden",
  },
  gradientButton: { flex: 1, justifyContent: "center", alignItems: "center" },
  buttonText: { color: "white", fontWeight: "bold", fontSize: 16 },
  sectionContainer: { paddingHorizontal: 20, marginTop: 25 },
  sectionTitle: {
    color: "white",
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 10,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  cardPlaceholder: {
    backgroundColor: "#1A1A1A",
    borderRadius: 15,
    height: 120,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  placeholderText: {
    color: "#444",
    marginTop: 5,
    fontSize: 12,
    textAlign: "center",
    paddingHorizontal: 20,
  },
  mapBadge: {
    position: "absolute",
    bottom: 10,
    right: 10,
    backgroundColor: "#7CF205",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  mapBadgeText: { fontSize: 8, fontWeight: "bold" },
  statsGrid: { flexDirection: "row", gap: 10 },
  bigCard: {
    flex: 0.4,
    height: 130,
    padding: 15,
    justifyContent: "space-between",
  },
  statsRightCol: { flex: 0.6, gap: 10 },
  statCard: { backgroundColor: "#1A1A1A", borderRadius: 15 },
  statCardRow: { flexDirection: "row", gap: 10, flex: 1 },
  smallCard: {
    flex: 1,
    backgroundColor: "#1A1A1A",
    borderRadius: 12,
    padding: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  statLabel: { color: "#888", fontSize: 10, fontWeight: "bold" },
  statValue: { color: "white", fontSize: 20, fontWeight: "900" },
  statLabelSmall: { color: "#888", fontSize: 8 },
  statValueSmall: { color: "white", fontSize: 11, fontWeight: "bold" },
  statIcon: { alignSelf: "flex-end" },
  miniPathLine: {
    height: 2,
    backgroundColor: "#444",
    width: "100%",
    marginTop: 5,
  },
  achievementScroll: { flexDirection: "row" },
  achievementItem: { alignItems: "center", marginRight: 25 },
  achievementCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#222",
    marginBottom: 8,
  },
  achievementTitle: { color: "white", fontSize: 12, fontWeight: "bold" },
  achievementProgress: { color: "#666", fontSize: 10 },
  backButton: {},
  menuButton: {},
});
