import { Dimensions, StyleSheet } from "react-native";
import { KARELA } from "./designSystem";

const { width } = Dimensions.get("window");

export const ProgressScreenUI = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: KARELA.color.bg,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: KARELA.space.xl,
    paddingTop: 50,
    paddingBottom: 10,
    alignItems: "center",
  },
  profileSection: {
    alignItems: "center",
    marginBottom: 10,
  },
  avatarWrapper: {
    width: 120,
    height: 120,
    borderRadius: 60,
    overflow: "hidden",
    marginBottom: 10,
  },
  avatarGradient: { flex: 1, padding: KARELA.space.xs },
  avatarImage: { flex: 1, borderRadius: 60, backgroundColor: KARELA.color.surface },
  rankText: {
    color: KARELA.color.textPrimary,
    fontSize: KARELA.size.h2,
    fontFamily: KARELA.font.black,
    letterSpacing: 1,
  },
  xpText: { color: KARELA.color.textFaint, fontSize: KARELA.size.label, fontFamily: KARELA.font.regular },
  rankButton: {
    margin: KARELA.space.xl,
    width: "60%",
    height: 45,
    borderRadius: 25,
    overflow: "hidden",
  },
  gradientButton: { flex: 1, justifyContent: "center", alignItems: "center" },
  buttonText: { color: KARELA.color.textPrimary, fontFamily: KARELA.font.bold, fontSize: 16 },

  sectionContainer: { paddingHorizontal: KARELA.space.xl, marginTop: 25 },
  sectionTitle: {
    color: KARELA.color.textPrimary,
    fontSize: KARELA.size.h2,
    fontFamily: KARELA.font.bold,
    marginBottom: 10,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: KARELA.space.md,
  },

  swipeWrapper: { marginTop: 15 },
  statsSlide: { width: width, paddingHorizontal: KARELA.space.xl },
  statsGrid: { flexDirection: "row", gap: 10 },
  bigCard: {
    flex: 0.43,
    height: 140,
    padding: 15,
    justifyContent: "space-between",
    backgroundColor: KARELA.color.surface,
    borderRadius: KARELA.radius.lg,
  },
  statsRightCol: { flex: 0.57, gap: 10 },
  statCard: { backgroundColor: KARELA.color.surface, borderRadius: KARELA.radius.lg },
  statCardRow: { flexDirection: "row", gap: 10, flex: 1 },
  smallCard: {
    flex: 1,
    backgroundColor: KARELA.color.surface,
    borderRadius: KARELA.radius.md,
    padding: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },

  statLabel: {
    color: KARELA.color.textMuted,
    fontSize: 11,
    fontFamily: KARELA.font.bold,
    textTransform: "uppercase",
  },
  statValue: { color: KARELA.color.textPrimary, fontSize: 22, fontFamily: KARELA.font.black },
  statLabelSmall: { color: KARELA.color.textMuted, fontSize: 9, fontFamily: KARELA.font.regular },
  statValueSmall: { color: KARELA.color.textPrimary, fontSize: KARELA.size.label, fontFamily: KARELA.font.bold },
  statIcon: { alignSelf: "flex-end", opacity: 0.6 },
  miniPathLine: {
    height: 3,
    backgroundColor: KARELA.color.brand,
    width: "40%",
    borderRadius: 2,
    marginTop: 5,
  },

  dotContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: KARELA.space.xl,
    gap: KARELA.space.sm,
  },
  dot: { width: 6, height: 6, borderRadius: 3, backgroundColor: KARELA.color.surfaceSoft },
  dotActive: { backgroundColor: KARELA.color.brand, width: 22 },
  activeIndicator: {
    backgroundColor: "rgba(124, 242, 5, 0.15)",
    paddingHorizontal: 10,
    paddingVertical: KARELA.space.xs,
    borderRadius: 6,
  },
  activeIndicatorText: { color: KARELA.color.brand, fontSize: 9, fontFamily: KARELA.font.black },

  cardPlaceholder: {
    backgroundColor: KARELA.color.surface,
    borderRadius: KARELA.radius.lg,
    height: 130,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
    borderWidth: 1,
    borderColor: KARELA.color.surfaceSoft,
  },
  placeholderText: {
    color: KARELA.color.textFaint,
    marginTop: KARELA.space.sm,
    fontSize: KARELA.size.label,
    fontFamily: KARELA.font.regular,
    textAlign: "center",
  },

  previewChartWrapper: {
    backgroundColor: "#111",
    borderRadius: KARELA.radius.xl,
    padding: KARELA.space.lg,
    marginTop: KARELA.space.md,
    borderWidth: 1,
    borderColor: KARELA.color.lineSoft,
  },
  daysRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
    paddingHorizontal: 2,
  },
  dayLabelMini: {
    color: KARELA.color.textFaint,
    fontSize: KARELA.size.caption,
    fontFamily: KARELA.font.bold,
    textAlign: "center",
    width: 20,
  },
  previewStatsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: KARELA.space.md,
    paddingTop: KARELA.space.md,
    borderTopWidth: 1,
    borderTopColor: KARELA.color.lineSoft,
  },
  miniStat: { color: KARELA.color.textMuted, fontSize: KARELA.size.label, fontFamily: KARELA.font.bold },
  viewDetailsText: { color: KARELA.color.brand, fontSize: KARELA.size.label, fontFamily: KARELA.font.bold },

  achievementScroll: { flexDirection: "row", marginTop: 5 },
  achievementItem: { alignItems: "center", marginRight: 25 },
  achievementCircle: {
    width: 75,
    height: 75,
    borderRadius: 38,
    backgroundColor: KARELA.color.surface,
    marginBottom: KARELA.space.sm,
    borderWidth: 1,
    borderColor: KARELA.color.surfaceSoft,
    justifyContent: "center",
    alignItems: "center",
  },
  achievementTitle: { color: KARELA.color.textPrimary, fontSize: KARELA.size.label, fontFamily: KARELA.font.bold },
  achievementProgress: { color: KARELA.color.textFaint, fontSize: KARELA.size.caption, marginTop: 2 },
  mapBadge: {
    position: "absolute",
    bottom: KARELA.space.md,
    right: KARELA.space.md,
    backgroundColor: KARELA.color.brand,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
  },
  mapBadgeText: { fontSize: 9, fontFamily: KARELA.font.bold, color: KARELA.color.onBright },
  backButton: { padding: 5 },
  menuButton: { padding: 5 },
});
